"""Derive `.env.docker` from the `backend/.env` this machine already runs on.

Same provider, same key, container-appropriate overrides. The secrets are
copied file-to-file and never printed: the summary is redacted.

    python scripts/env_for_docker.py [--force]
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "backend" / ".env"
TARGET = ROOT / ".env.docker"

# Blank on purpose: these name fine-tuned checkpoints served by a local ollama,
# which no container can reach. Blank falls back to the hosted model.
OVERRIDES = {
    "DEBUG": "false",
    "GENERATOR_MODEL": "",
    "EVALUATOR_MODEL": "",
    # The code default is large-v3, which was OOM-killed in a 3.674GB container
    # (exit 137) on 2026-09-03. small.en transcribed the same probe verbatim in
    # 28s at 1.33GB. Raise it deliberately on a host with the memory.
    "WHISPER_MODEL": "small.en",
}

# Suffixes, not substrings: LLM_MAX_TOKENS is a number, not a credential.
SECRET_SUFFIXES = ("_KEY", "_SECRET", "_TOKEN", "_PASSWORD")

# Local-only settings that mean nothing in a container, or would point it at a
# host path that does not exist there.
DROP = {"OLLAMA_BASE_URL", "OLLAMA_MODEL", "DATA_DIR", "UPLOAD_DIR",
        "QDRANT_PATH", "DATABASE_URL"}


def is_secret(key: str) -> bool:
    return key.endswith(SECRET_SUFFIXES)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true",
                        help="overwrite an existing .env.docker")
    args = parser.parse_args()

    if not SOURCE.exists():
        print(f"! {SOURCE} not found — copy .env.docker.example by hand instead.")
        return 1
    if TARGET.exists() and not args.force:
        print(f"! {TARGET} already exists. Re-run with --force to replace it.")
        return 1

    values: dict[str, str] = {}
    for line in SOURCE.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        key = key.strip()
        if key in DROP:
            continue
        values[key] = value.strip().strip('"').strip("'")

    values.update(OVERRIDES)

    # DEBUG=false means the placeholder secret is now fatal rather than a
    # warning, so a run that was fine locally would refuse to start here.
    if values.get("JWT_SECRET", "") in ("", "change-me-in-production"):
        values["JWT_SECRET"] = secrets.token_urlsafe(48)
        generated = True
    else:
        generated = False

    values.setdefault("CORS_ORIGINS", "*")

    body = [
        "# Generated by scripts/env_for_docker.py from backend/.env.",
        "# Secrets live here. Not committed — see .gitignore.",
        "",
    ]
    body += [f"{key}={value}" for key, value in values.items()]
    TARGET.write_text("\n".join(body) + "\n", encoding="utf-8")

    print(f"wrote {TARGET.relative_to(ROOT)}")
    for key, value in values.items():
        shown = "<set>" if is_secret(key) and value else ("<empty>" if value == "" else value)
        print(f"  {key}={shown}")
    if generated:
        print("\nJWT_SECRET was the placeholder or missing — generated a fresh one.")
        print("Existing logins signed with the old value stop working; students log in again.")
    if not values.get("OPENAI_API_KEY") and values.get("LLM_PROVIDER") == "openai":
        print("\n! OPENAI_API_KEY is empty. The app will serve pages and fail every")
        print("  generation call with an upstream 401 until you fill it in.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
